[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npx prisma generate && npm run build"]

[start]
cmd = "cd backend && npm start"
